services:
  - type: web
    name: kimbap-server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DDL_AUTO
        value: create
